### ISSUE TITLE
configure shouts out a warning; package/executable name; mtree.5 man page

### ISSUE THREAD

**Issue by brucelilly** [archiecobbs/nmtree#1]
Configure screams:
config.status: creating Makefile
config.status: WARNING:  'Makefile.in' seems to ignore the --datarootdir setting
config.status: creating config.h

Name the package whatever you like, but I don't think renaming the executable is a good idea, especially since the man page is still mtree(8) (and references /etc/mtree).

Speaking of man pages, adding mtree(5) would be useful: you can find the file at
http://ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/external/bsd/libarchive/dist/libarchive/mtree.5
It should probably be added to the list of files to be installed.

**Comment by archiecobbs** [comment]
Should be fixed in a75b5be.
